// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmHLpbeGG9NsvZlJQhXuo_Ut1lnX4iHmE',
    appId: '1:547830533596:web:acbf37409b728ad4d6d319',
    messagingSenderId: '547830533596',
    projectId: 'hifixit-66d2b',
    authDomain: 'hifixit-66d2b.firebaseapp.com',
    databaseURL: 'https://hifixit-66d2b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hifixit-66d2b.appspot.com',
    measurementId: 'G-YTG5XVCZR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6hDo-r2R7bdq_e3yf8ogwsdlHvxcEUcU',
    appId: '1:547830533596:android:ffc1340dccc7303ed6d319',
    messagingSenderId: '547830533596',
    projectId: 'hifixit-66d2b',
    databaseURL: 'https://hifixit-66d2b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hifixit-66d2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeRbwm0Llp6vwwxdMNLSt3njOJ7gjV4jA',
    appId: '1:547830533596:ios:47ddcff43dfd8eedd6d319',
    messagingSenderId: '547830533596',
    projectId: 'hifixit-66d2b',
    databaseURL: 'https://hifixit-66d2b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hifixit-66d2b.appspot.com',
    androidClientId: '547830533596-a7b505ohqu7paotp9tsqntth0b33mjf8.apps.googleusercontent.com',
    iosClientId: '547830533596-ke7j2mvufien87eq5b09o2q675i1f8pa.apps.googleusercontent.com',
    iosBundleId: 'com.anisa.hifixit',
  );
}
